using System.Text;
using Microsoft.CodeAnalysis;

namespace nyingi.Kafa.Generators;

internal sealed partial class KafaSourceGenerator
{
    private static void Emit(SourceProductionContext context, TypeDefinitionContext source)
    {
        StringBuilder builder = new StringBuilder();
        string Namespace =
            "{(source.Namespace is null ? String.Empty : $\"namespace {source.Namespace};{Environment.NewLine}\")}";
        
        // lang=c#
        string classDef = $@"
// <auto-generated/>

#nullable enable

{Namespace}
partial class {source.Name}
    {{

        
    }}
";
        
    }

    private static string EmitSerializer(TypeDefinitionContext source)
    {

        // lang=c#
        string serializer = $@"
        public static void Serializer(global::System.Collections.Generic.List<{source.Name}> entities, ref nyingi.Kafa.Writer.KafaWriter writer)
        {{
            
        }}
";
        return "";
    }

    private static string EmitDeserializer(TypeDefinitionContext source)
    {
        // lang=c#
        string deserializer = $@"
        {GeneratedAttribute}
        public static global::System.Collections.Generic.List<{source.Name}> Deserialize(nyingi.Kafa.Reader.RowEnumerable rows)
        {{
            var results = new global::System.Collections.Generic.List<{source.Name}>(rows.Length);
            
            
        }}
";
        return "";
    }
}