namespace nyingi.Kafa.Generators;

internal sealed partial class KafaSourceGenerator
{
    private static readonly string GeneratedAttribute = $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(KafaSourceGenerator).Assembly.GetName().Name}"", ""{typeof(KafaSourceGenerator).Assembly.GetName().Version}"")]";
    
    //lang=c#
    private static readonly string KafaSerializableAttribute = $@"
//<auto-generated/>

#nullable enable

namespace nyingi.Kafa;

{GeneratedAttribute}
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple =true, Inherited = false)]
public sealed class KafaSerializableAttribute : global::System.Attribute
{{
    public global::System.Type Type {{ get; }}

    public KafaSerializableAttribute(global::System.Type type)
    {{
        Type = type;
    }}
}}
";
}