using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace nyingi.Kafa.Generators;

internal sealed partial class KafaSourceGenerator
{
    private static void Emit(SourceProductionContext context, TypeDefinitionContext source)
    {
        string @namespace = (source.NameSpace is null
            ? String.Empty
            : $"namespace {source.NameSpace};{Environment.NewLine}");
        StringBuilder stringBuilder = new StringBuilder();
        // lang=c#
        stringBuilder.Append($@"
// <auto-generated/>

#nullable enable

using global::nyingi.Kafa;

{@namespace}
partial class {source.Name}
    {{"); 
        stringBuilder.Append("}");
        
        context.AddSource("KafaSerializerGenerator.g.cs", stringBuilder.ToString());
    }
}